Enable basic watching of geolocation
metonym/svelte-geolocation pull request #1
Opened 2021-01-29 22:56 UTC by dritter

Hi there, this is a draft for implementing `geolocation.watchPosition()`.

This is not yet complete, as this has several flaws:
- [ ] The `watch` prop is not fully reactive, as `getPosition` has to be toggled to reenable watching position.
- [ ] Not documented yet

And generally speaking: having two booleans that trigger the geolocation API feels odd. But I am not sure what the best way is to solve this. Could be by giving `getPosition` more meaning (making it a String).
Another idea (not sure if that would work) is to provide a slot for the getPosition-Button, and another one for the watch-Button and listen to the click event (like [here](https://github.com/sveltejs/sapper/issues/731#issuecomment-500487405)).. But I think this would be a dirty solution..

WDYT?

2021-01-29 23:04 UTC, metonym commented
Supporting the `watchPosition` API would be a great feature.

> And generally speaking: having two booleans that trigger the geolocation API feels odd.

What's your use case? Do you need to both get/watch APIs, or just one?

I think that exporting functions to trigger each of the APIs might be worth exploring. This would enable the consumer to programmatically trigger the API without the booleans.

```svelte
<script>
  let ref;

  $: if (ref) ref.getPosition();
</script>

<Geolocation bind:this={ref} />
```

2021-01-29 23:08 UTC, dritter commented
> What's your use case? Do you need to both get/watch APIs, or just one?

I just need watch, but in my current implementation I would need to set `getPosition` to trigger it initially.

> This would enable the consumer to programmatically trigger the API without the booleans.

That is a great idea. I'll try that in the next days.

2021-01-30 23:53 UTC, dritter commented
Okay. I just reworked it towards exporting the functions. That feels better to me, with the downside of having to do the wiring from outside is still a bit odd.

Another idea came into my mind: Why not split it into different components? That would make it clear to the dev how to use them (could be `<GeolocationTrackPosition>` and `<GeolocationGetPosition>` or similar) without having to do the wiring.

2021-01-31 00:05 UTC, metonym commented
> Why not split it into different components? That would make it clear to the dev how to use them (could be <GeolocationTrackPosition> and <GeolocationGetPosition> or similar) without having to do the wiring

Do you mean having separate components while using a boolean as a trigger? Or try this new programmatic approach?

2021-01-31 11:57 UTC, dritter commented
Neither ;)

If I understand correctly, the boolean trigger is there only to avoid the "Only request geolocation information in response to a user gesture" Violation Warning. This is a fancy way of doing:
```svelte
<script>
  let getPosition = false;
</script>
<button on:click={getPosition = true}>Find Stores near me</button>
{#if getPosition}
  <Geolocation>
{/if}
```
So if this is properly documented, we could just remove the booleans, or am I missing something?

Maybe the component is then simple enough that it could have a `watch` prop (so that we keep a single component). If not, we could split them.

Sorry for bringing up new ideas.

2021-01-31 14:28 UTC, metonym commented
I'd prefer keeping both methods:

- boolean as a trigger
- exporting a function

2021-01-31 23:13 UTC, dritter commented
Okay. Let's keep it then.

PTAL

2021-01-31 23:31 UTC, metonym requested changes
The TypeScript definitions need to be updated as well

2021-01-31 23:31 UTC, metonym commented on src/Geolocation.svelte
> +  import { createEventDispatcher, onDestroy } from 'svelte'
```suggestion
  import { createEventDispatcher, onDestroy } from "svelte";
```

Double quotes and a semicolon

2021-01-31 23:31 UTC, metonym commented on src/Geolocation.svelte
> +  let lastPosition = undefined;
```suggestion
  let lastPosition = undefined;
  
```

Blank line

2021-02-01 18:38 UTC, dritter commented
Okay, I added your suggestions. Not sure if I did everything right with the typescript definitions.

2021-02-01 19:05 UTC, metonym commented
@dritter I should have been more explicit. The type definitions are located in this file: https://github.com/metonym/svelte-geolocation/blob/master/types/Geolocation.d.ts

2021-02-01 19:29 UTC, dritter commented
Ha. Thanks for your guidance. I added the `watch` definition and updated the definition for `getPosition`.

2021-02-02 00:39 UTC, metonym approved these changes
Great work. Thanks for taking this on.

2021-02-02 00:39 UTC, merged

2021-02-02 00:49 UTC, metonym commented
Published v0.2.0 to NPM.